In [1]:
#main/notebooks/01_read.ipynb
import os
import sys

project_root = os.path.abspath('..')

if project_root not in sys.path:
    sys.path.append(project_root)

import pandas as pd
from src.data_cleaning import preprocess_column
%run ../src/config.py

In [2]:
# datos = "C:/Users/Jaime/Desktop/Jaime/Universidad/Curso4/TFG/analisis_dataset/.idea/analisis/csv/imdb-movies-dataset.csv"
df = pd.read_csv(filepath_or_buffer="../data/raw/imdb-movies-dataset.csv", sep=",")

In [3]:
df.head()

,Poster,Title,Year,Certificate,Duration (min),Genre,Rating,Metascore,Director,Cast,Votes,Description,Review Count,Review Title,Review
0,https://m.media-amazon.com/images/M/MV5BYWRkZj...,The Idea of You,2023.0,R,115.0,"Comedy, Drama, Romance",6.4,67.0,Michael Showalter,"Anne Hathaway, Nicholas Galitzine, Ella Rubin,...","28,744","Solène, a 40-year-old single mom, begins an un...",166,Hypocrisy as an idea,"This film, as well as the reaction to it, is a..."
1,https://m.media-amazon.com/images/M/MV5BZGI4NT...,Kingdom of the Planet of the Apes,2023.0,PG-13,145.0,"Action, Adventure, Sci-Fi",7.3,66.0,Wes Ball,"Owen Teague, Freya Allan, Kevin Durand, Peter ...","22,248","Many years after the reign of Caesar, a young ...",183,A phenomenal start to another trilogy!,"I'm a big fan of all the planet of the apes, a..."
2,https://m.media-amazon.com/images/M/MV5BZjIyOT...,Unfrosted,2023.0,PG-13,97.0,"Biography, Comedy, History",5.5,42.0,Jerry Seinfeld,"Isaac Bae, Jerry Seinfeld, Chris Rickett, Rach...","18,401","In 1963 Michigan, business rivals Kellogg's an...",333,not funny,Pretty much the worst criticism you can lay on...
3,https://m.media-amazon.com/images/M/MV5BMjA5Zj...,The Fall Guy,2023.0,PG-13,126.0,"Action, Comedy, Drama",7.3,73.0,David Leitch,"Ryan Gosling, Emily Blunt, Aaron Taylor-Johnso...","38,953",A down-and-out stuntman must find the missing ...,384,Everything you needed and more!,Just got out of the Austin premier at SXSW and...
4,https://m.media-amazon.com/images/M/MV5BNTk1MT...,Challengers,2023.0,R,131.0,"Drama, Romance, Sport",7.7,82.0,Luca Guadagnino,"Zendaya, Mike Faist, Josh O'Connor, Darnell Ap...","32,517","Tashi, a former tennis prodigy turned coach, t...",194,"Watch ""Match Point"" instead",This is a tough one. I liked the concept and t...

In [4]:
pd.isnull(df).sum()

Poster               0
Title                0
Year               150
Certificate       2630
Duration (min)     336
Genre                7
Rating             404
Metascore         2445
Director             5
Cast                39
Votes              404
Description          0
Review Count         1
Review Title       517
Review             516
dtype: int64

In [5]:
pd.isnull(df['Genre'])

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: Genre, Length: 10000, dtype: bool

In [6]:
df

,Poster,Title,Year,Certificate,Duration (min),Genre,Rating,Metascore,Director,Cast,Votes,Description,Review Count,Review Title,Review
0,https://m.media-amazon.com/images/M/MV5BYWRkZj...,The Idea of You,2023.0,R,115.0,"Comedy, Drama, Romance",6.4,67.0,Michael Showalter,"Anne Hathaway, Nicholas Galitzine, Ella Rubin,...","28,744","Solène, a 40-year-old single mom, begins an un...",166,Hypocrisy as an idea,"This film, as well as the reaction to it, is a..."
1,https://m.media-amazon.com/images/M/MV5BZGI4NT...,Kingdom of the Planet of the Apes,2023.0,PG-13,145.0,"Action, Adventure, Sci-Fi",7.3,66.0,Wes Ball,"Owen Teague, Freya Allan, Kevin Durand, Peter ...","22,248","Many years after the reign of Caesar, a young ...",183,A phenomenal start to another trilogy!,"I'm a big fan of all the planet of the apes, a..."
2,https://m.media-amazon.com/images/M/MV5BZjIyOT...,Unfrosted,2023.0,PG-13,97.0,"Biography, Comedy, History",5.5,42.0,Jerry Seinfeld,"Isaac Bae, Jerry Seinfeld, Chris Rickett, Rach...","18,401","In 1963 Michigan, business rivals Kellogg's an...",333,not funny,Pretty much the worst criticism you can lay on...
3,https://m.media-amazon.com/images/M/MV5BMjA5Zj...,The Fall Guy,2023.0,PG-13,126.0,"Action, Comedy, Drama",7.3,73.0,David Leitch,"Ryan Gosling, Emily Blunt, Aaron Taylor-Johnso...","38,953",A down-and-out stuntman must find the missing ...,384,Everything you needed and more!,Just got out of the Austin premier at SXSW and...
4,https://m.media-amazon.com/images/M/MV5BNTk1MT...,Challengers,2023.0,R,131.0,"Drama, Romance, Sport",7.7,82.0,Luca Guadagnino,"Zendaya, Mike Faist, Josh O'Connor, Darnell Ap...","32,517","Tashi, a former tennis prodigy turned coach, t...",194,"Watch ""Match Point"" instead",This is a tough one. I liked the concept and t...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,https://m.media-amazon.com/images/M/MV5BMzg5MW...,The Greatest Show on Earth,2020.0,U,152.0,"Drama, Family, Romance",6.5,76.0,Cecil B. DeMille,"James Stewart, Charlton Heston, Betty Hutton, ...","16,078","The dramatic lives of trapeze artists, a clown...",128,"Hey, doesn't anyone remember Last Emperor?",It constantly amazes me that people carp that ...
9996,https://m.media-amazon.com/images/M/MV5BYzA0ZG...,Berserk: Ougon Jidai-hen I - Haou no Tamago,2020.0,NaN,76.0,"Animation, Action, Adventure",7.5,NaN,Toshiyuki Kubooka,"Hiroaki Iwanaga, Carrie Keranen, Takahiro Saku...","14,300",A lone sellsword named Guts gets recruited int...,12,Masterfully directed climatic epic saga,Few stories can capture your mind and soul in ...
9997,https://m.media-amazon.com/images/M/MV5BM2U1Mj...,Is-slottet,2020.0,NaN,78.0,"Mystery, Drama",6.5,NaN,Per Blom,"Line Storesund, Hilde Nyeggen Martinsen, Meret...",740,A couple of twelve-year-old Norwegian girls st...,4,Beautiful Film,"This film might not be to everyone's taste, it..."
9998,https://m.media-amazon.com/images/M/MV5BMTAwOD...,Loving Pablo,2020.0,A,123.0,"Biography, Crime, Drama",6.4,42.0,Fernando León de Aranoa,"Javier Bardem, Penélope Cruz, Peter Sarsgaard,...","22,447",A journalist strikes up a romantic relationshi...,84,That film should be in Spanish,Why anyone (the director?) made Spanish actors...
9999,https://m.media-amazon.com/images/M/MV5BMmE4ZD...,Un homme et une femme,2020.0,NaN,102.0,"Drama, Romance",7.5,NaN,Claude Lelouch,"Anouk Aimée, Jean-Louis Trintignant, Pierre Ba...","11,826",A widow and a widower find their relationship ...,61,Moved me tremendously.,This is a movie that resonated to my core. I ...

In [7]:
df = df.drop(columns=['Certificate'])
df.head()

,Poster,Title,Year,Duration (min),Genre,Rating,Metascore,Director,Cast,Votes,Description,Review Count,Review Title,Review
0,https://m.media-amazon.com/images/M/MV5BYWRkZj...,The Idea of You,2023.0,115.0,"Comedy, Drama, Romance",6.4,67.0,Michael Showalter,"Anne Hathaway, Nicholas Galitzine, Ella Rubin,...","28,744","Solène, a 40-year-old single mom, begins an un...",166,Hypocrisy as an idea,"This film, as well as the reaction to it, is a..."
1,https://m.media-amazon.com/images/M/MV5BZGI4NT...,Kingdom of the Planet of the Apes,2023.0,145.0,"Action, Adventure, Sci-Fi",7.3,66.0,Wes Ball,"Owen Teague, Freya Allan, Kevin Durand, Peter ...","22,248","Many years after the reign of Caesar, a young ...",183,A phenomenal start to another trilogy!,"I'm a big fan of all the planet of the apes, a..."
2,https://m.media-amazon.com/images/M/MV5BZjIyOT...,Unfrosted,2023.0,97.0,"Biography, Comedy, History",5.5,42.0,Jerry Seinfeld,"Isaac Bae, Jerry Seinfeld, Chris Rickett, Rach...","18,401","In 1963 Michigan, business rivals Kellogg's an...",333,not funny,Pretty much the worst criticism you can lay on...
3,https://m.media-amazon.com/images/M/MV5BMjA5Zj...,The Fall Guy,2023.0,126.0,"Action, Comedy, Drama",7.3,73.0,David Leitch,"Ryan Gosling, Emily Blunt, Aaron Taylor-Johnso...","38,953",A down-and-out stuntman must find the missing ...,384,Everything you needed and more!,Just got out of the Austin premier at SXSW and...
4,https://m.media-amazon.com/images/M/MV5BNTk1MT...,Challengers,2023.0,131.0,"Drama, Romance, Sport",7.7,82.0,Luca Guadagnino,"Zendaya, Mike Faist, Josh O'Connor, Darnell Ap...","32,517","Tashi, a former tennis prodigy turned coach, t...",194,"Watch ""Match Point"" instead",This is a tough one. I liked the concept and t...

In [8]:
pd.isnull(df).sum()

Poster               0
Title                0
Year               150
Duration (min)     336
Genre                7
Rating             404
Metascore         2445
Director             5
Cast                39
Votes              404
Description          0
Review Count         1
Review Title       517
Review             516
dtype: int64

In [9]:
values_null = df[df.isnull().any(axis=1)]
print(values_null)

                                                 Poster  \
7     https://m.media-amazon.com/images/M/MV5BZTc3Ym...
17    https://m.media-amazon.com/images/M/MV5BYWQ4OG...
18    https://m.media-amazon.com/images/M/MV5BZTQyZW...
20    https://m.media-amazon.com/images/M/MV5BYTdkOT...
21    https://m.media-amazon.com/images/M/MV5BOWI2Yj...
...                                                 ...
9987  https://m.media-amazon.com/images/M/MV5BNmYxMG...
9991  https://m.media-amazon.com/images/M/MV5BMjFkZG...
9996  https://m.media-amazon.com/images/M/MV5BYzA0ZG...
9997  https://m.media-amazon.com/images/M/MV5BM2U1Mj...
9999  https://m.media-amazon.com/images/M/MV5BMmE4ZD...

                                            Title    Year  Duration (min)  \
7                                        Twisters  2023.0             NaN
17                                             IF  2023.0           104.0
18                                    Megalopolis  2023.0           133.0
20                                Laapataa Ladies  2023.0           122.0
21                           Deadpool & Wolverine  2023.0             NaN
...                                           ...     ...             ...
9987                            Dracula A.D. 1972  2020.0            96.0
9991                               Beyond the Law  2020.0            89.0
9996  Berserk: Ougon Jidai-hen I - Haou no Tamago  2020.0            76.0
9997                                   Is-slottet  2020.0            78.0
9999                        Un homme et une femme  2020.0           102.0

                             Genre  Rating  Metascore               Director  \
7      Action, Adventure, Thriller     NaN        NaN        Lee Isaac Chung
17        Animation, Comedy, Drama     6.8        NaN         John Krasinski
18                   Drama, Sci-Fi     NaN        NaN   Francis Ford Coppola
20                   Comedy, Drama     8.5        NaN              Kiran Rao
21          Action, Comedy, Sci-Fi     NaN        NaN             Shawn Levy
...                            ...     ...        ...                    ...
9987                        Horror     5.9        NaN            Alan Gibson
9991       Action, Crime, Thriller     3.7        NaN  James Cullen Bressack
9996  Animation, Action, Adventure     7.5        NaN      Toshiyuki Kubooka
9997                Mystery, Drama     6.5        NaN               Per Blom
9999                Drama, Romance     7.5        NaN         Claude Lelouch

                                                   Cast   Votes  \
7     Daisy Edgar-Jones, Glen Powell, David Corenswe...     NaN
17    Cailey Fleming, Ryan Reynolds, John Krasinski,...     906
18    Nathalie Emmanuel, Shia LaBeouf, Giancarlo Esp...     NaN
20    Nitanshi Goel, Pratibha Ranta, Sparsh Srivasta...  20,957
21    Ryan Reynolds, Hugh Jackman, Emma Corrin, More...     NaN
...                                                 ...     ...
9987  Christopher Lee, Peter Cushing, Stephanie Beac...   7,453
9991     Johnny Messner, Steven Seagal, DMX, Bill Cobbs   3,175
9996  Hiroaki Iwanaga, Carrie Keranen, Takahiro Saku...  14,300
9997  Line Storesund, Hilde Nyeggen Martinsen, Meret...     740
9999  Anouk Aimée, Jean-Louis Trintignant, Pierre Ba...  11,826

                                            Description Review Count  \
7     An update to the 1996 film 'Twister', which ce...            0
17    A young girl who goes through a difficult expe...           15
18    An architect wants to rebuild New York City as...            1
20    The misadventures of two young brides who get ...          209
21    Wolverine is recovering from his injuries when...            0
...                                                 ...          ...
9987  In 1972 London - a century after his final bat...           98
9991  A mobster trying to go straight and a dogged p...           54
9996  A lone sellsword named Guts gets recruited int...           12
9997  A couple of twelve-year-old Norwegian girls st...            4
9999  A widow and a widower find their relationship ...           61

                                 Review Title  \
7                                         NaN
17               30 year old male perspective
18              You should refuse this offer.
20               Movie is not good, avoid it.
21                                        NaN
...                                       ...
9987                Work of accidental genius
9991                               Snoozefest
9996  Masterfully directed climatic epic saga
9997                           Beautiful Film
9999                   Moved me tremendously.

                                                 Review
7                                                   NaN
17    I must admit, the first half hour had me quest...
18    FFC is an egomaniac to the force he spent his ...
20    After watching youtubers reviews, many of them...
21                                                  NaN
...                                                 ...
9987  Although it feels a bit thrown together, with ...
9991  Absolutely awful, Steven segal needs to stop m...
9996  Few stories can capture your mind and soul in ...
9997  This film might not be to everyone's taste, it...
9999  This is a movie that resonated to my core.  I ...

[2556 rows x 14 columns]

In [10]:
df = df.dropna(subset=['Duration (min)', 'Review', 'Cast', 'Review Title', 'Year', 'Votes'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9336 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Poster          9336 non-null   object
 1   Title           9336 non-null   object
 2   Year            9336 non-null   float64
 3   Duration (min)  9336 non-null   float64
 4   Genre           9336 non-null   object
 5   Rating          9336 non-null   float64
 6   Metascore       7444 non-null   float64
 7   Director        9336 non-null   object
 8   Cast            9336 non-null   object
 9   Votes           9336 non-null   object
 10  Description     9336 non-null   object
 11  Review Count    9336 non-null   object
 12  Review Title    9336 non-null   object
 13  Review          9336 non-null   object
dtypes: float64(4), object(10)
memory usage: 1.1+ MB

In [11]:
df['metascore_missing'] = df['Metascore'].isna().astype(int)    # comprueba fila a fila si el dato metascore es nan, si falta -> true, en caso contrario, false, .astype devuelve la lista convirtiendo los valores booleanos a números enteros (0/1)
df['Metascore'].fillna(df['Metascore'].median(), inplace=True)  # calcula la mediana para el valor metascore faltante, es decir, NaN, con inplace=True, le damos permiso para modificarlo directamente

df['Rating'] = df['Rating'].fillna(df['Rating'].median())
df.head()
df.info()

C:\Users\Jaime\AppData\Local\Temp\ipykernel_7076\3422811140.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Metascore'].fillna(df['Metascore'].median(), inplace=True)

In [12]:
pd.isnull(df).sum()

Poster               0
Title                0
Year                 0
Duration (min)       0
Genre                0
Rating               0
Metascore            0
Director             0
Cast                 0
Votes                0
Description          0
Review Count         0
Review Title         0
Review               0
metascore_missing    0
dtype: int64

In [13]:
df['reviews_tokenizadas'] = [preprocess_column(i) for i in df['Review']]
# resultado = preprocess_column(df['Review'])

In [14]:
# df['Review'] = df['Review'].apply(word_tokenize)
df[['Review', 'reviews_tokenizadas']].head()

,Review,reviews_tokenizadas
0,"This film, as well as the reaction to it, is a...",film well reaction wonderful example modern hy...
1,"I'm a big fan of all the planet of the apes, a...",big fan planet ape nailed one usually start mi...
2,Pretty much the worst criticism you can lay on...,pretty much worst criticism lay comedian true ...
3,Just got out of the Austin premier at SXSW and...,got austin premier sxsw whole theatre went nut...
4,This is a tough one. I liked the concept and t...,tough one liked concept overall story however ...

In [15]:
#df['Review Title'] = [preprocess_column(i) for i in df['Review Title']]
#df['Description'] = [preprocess_column(i) for i in df['Description']]

In [16]:
df_tokenizado = df.explode(column='reviews_tokenizadas')
df_tokenizado = df_tokenizado.drop(columns='Review')
df_tokenizado = df_tokenizado.rename(columns={'reviews_tokenizadas': 'token'})
df_tokenizado.head()

,Poster,Title,Year,Duration (min),Genre,Rating,Metascore,Director,Cast,Votes,Description,Review Count,Review Title,metascore_missing,token
0,https://m.media-amazon.com/images/M/MV5BYWRkZj...,The Idea of You,2023.0,115.0,"Comedy, Drama, Romance",6.4,67.0,Michael Showalter,"Anne Hathaway, Nicholas Galitzine, Ella Rubin,...","28,744","Solène, a 40-year-old single mom, begins an un...",166,Hypocrisy as an idea,0,film well reaction wonderful example modern hy...
1,https://m.media-amazon.com/images/M/MV5BZGI4NT...,Kingdom of the Planet of the Apes,2023.0,145.0,"Action, Adventure, Sci-Fi",7.3,66.0,Wes Ball,"Owen Teague, Freya Allan, Kevin Durand, Peter ...","22,248","Many years after the reign of Caesar, a young ...",183,A phenomenal start to another trilogy!,0,big fan planet ape nailed one usually start mi...
2,https://m.media-amazon.com/images/M/MV5BZjIyOT...,Unfrosted,2023.0,97.0,"Biography, Comedy, History",5.5,42.0,Jerry Seinfeld,"Isaac Bae, Jerry Seinfeld, Chris Rickett, Rach...","18,401","In 1963 Michigan, business rivals Kellogg's an...",333,not funny,0,pretty much worst criticism lay comedian true ...
3,https://m.media-amazon.com/images/M/MV5BMjA5Zj...,The Fall Guy,2023.0,126.0,"Action, Comedy, Drama",7.3,73.0,David Leitch,"Ryan Gosling, Emily Blunt, Aaron Taylor-Johnso...","38,953",A down-and-out stuntman must find the missing ...,384,Everything you needed and more!,0,got austin premier sxsw whole theatre went nut...
4,https://m.media-amazon.com/images/M/MV5BNTk1MT...,Challengers,2023.0,131.0,"Drama, Romance, Sport",7.7,82.0,Luca Guadagnino,"Zendaya, Mike Faist, Josh O'Connor, Darnell Ap...","32,517","Tashi, a former tennis prodigy turned coach, t...",194,"Watch ""Match Point"" instead",0,tough one liked concept overall story however ...

In [17]:
# df_tokenizado.groupby(by='Title')['token'].count()

In [18]:
# eng_stopwords = stopwords.words('english')
# df['Review'] = df['Review'].apply(lambda words: [word for word in words if word not in eng_stopwords])

In [19]:
df.head()

,Poster,Title,Year,Duration (min),Genre,Rating,Metascore,Director,Cast,Votes,Description,Review Count,Review Title,Review,metascore_missing,reviews_tokenizadas
0,https://m.media-amazon.com/images/M/MV5BYWRkZj...,The Idea of You,2023.0,115.0,"Comedy, Drama, Romance",6.4,67.0,Michael Showalter,"Anne Hathaway, Nicholas Galitzine, Ella Rubin,...","28,744","Solène, a 40-year-old single mom, begins an un...",166,Hypocrisy as an idea,"This film, as well as the reaction to it, is a...",0,film well reaction wonderful example modern hy...
1,https://m.media-amazon.com/images/M/MV5BZGI4NT...,Kingdom of the Planet of the Apes,2023.0,145.0,"Action, Adventure, Sci-Fi",7.3,66.0,Wes Ball,"Owen Teague, Freya Allan, Kevin Durand, Peter ...","22,248","Many years after the reign of Caesar, a young ...",183,A phenomenal start to another trilogy!,"I'm a big fan of all the planet of the apes, a...",0,big fan planet ape nailed one usually start mi...
2,https://m.media-amazon.com/images/M/MV5BZjIyOT...,Unfrosted,2023.0,97.0,"Biography, Comedy, History",5.5,42.0,Jerry Seinfeld,"Isaac Bae, Jerry Seinfeld, Chris Rickett, Rach...","18,401","In 1963 Michigan, business rivals Kellogg's an...",333,not funny,Pretty much the worst criticism you can lay on...,0,pretty much worst criticism lay comedian true ...
3,https://m.media-amazon.com/images/M/MV5BMjA5Zj...,The Fall Guy,2023.0,126.0,"Action, Comedy, Drama",7.3,73.0,David Leitch,"Ryan Gosling, Emily Blunt, Aaron Taylor-Johnso...","38,953",A down-and-out stuntman must find the missing ...,384,Everything you needed and more!,Just got out of the Austin premier at SXSW and...,0,got austin premier sxsw whole theatre went nut...
4,https://m.media-amazon.com/images/M/MV5BNTk1MT...,Challengers,2023.0,131.0,"Drama, Romance, Sport",7.7,82.0,Luca Guadagnino,"Zendaya, Mike Faist, Josh O'Connor, Darnell Ap...","32,517","Tashi, a former tennis prodigy turned coach, t...",194,"Watch ""Match Point"" instead",This is a tough one. I liked the concept and t...,0,tough one liked concept overall story however ...

In [20]:
# lemmatizer = WordNetLemmatizer()
# lemmatizer_tokens = df['Review'].apply(lambda words: [lemmatizer.lemmatize(word) for word in words])

In [21]:
df = df.drop(columns=['Poster'])
df.head()

,Title,Year,Duration (min),Genre,Rating,Metascore,Director,Cast,Votes,Description,Review Count,Review Title,Review,metascore_missing,reviews_tokenizadas
0,The Idea of You,2023.0,115.0,"Comedy, Drama, Romance",6.4,67.0,Michael Showalter,"Anne Hathaway, Nicholas Galitzine, Ella Rubin,...","28,744","Solène, a 40-year-old single mom, begins an un...",166,Hypocrisy as an idea,"This film, as well as the reaction to it, is a...",0,film well reaction wonderful example modern hy...
1,Kingdom of the Planet of the Apes,2023.0,145.0,"Action, Adventure, Sci-Fi",7.3,66.0,Wes Ball,"Owen Teague, Freya Allan, Kevin Durand, Peter ...","22,248","Many years after the reign of Caesar, a young ...",183,A phenomenal start to another trilogy!,"I'm a big fan of all the planet of the apes, a...",0,big fan planet ape nailed one usually start mi...
2,Unfrosted,2023.0,97.0,"Biography, Comedy, History",5.5,42.0,Jerry Seinfeld,"Isaac Bae, Jerry Seinfeld, Chris Rickett, Rach...","18,401","In 1963 Michigan, business rivals Kellogg's an...",333,not funny,Pretty much the worst criticism you can lay on...,0,pretty much worst criticism lay comedian true ...
3,The Fall Guy,2023.0,126.0,"Action, Comedy, Drama",7.3,73.0,David Leitch,"Ryan Gosling, Emily Blunt, Aaron Taylor-Johnso...","38,953",A down-and-out stuntman must find the missing ...,384,Everything you needed and more!,Just got out of the Austin premier at SXSW and...,0,got austin premier sxsw whole theatre went nut...
4,Challengers,2023.0,131.0,"Drama, Romance, Sport",7.7,82.0,Luca Guadagnino,"Zendaya, Mike Faist, Josh O'Connor, Darnell Ap...","32,517","Tashi, a former tennis prodigy turned coach, t...",194,"Watch ""Match Point"" instead",This is a tough one. I liked the concept and t...,0,tough one liked concept overall story however ...

In [22]:
df['Review'][0]

"This film, as well as the reaction to it, is a wonderful example of modern hypocrisy:The story is about an adult woman who is attracted to a young guy, 16 years younger than her, young enough to be her son, whom she sees at his boys band concert, and from people reactions starts from the movie trailer and beyond, we get praise and stories that this is the destruction of the stigma about the happiness of a woman at 40, that she can remain attractive at any age to any man, that happiness is available to anyone and it's not for us to judge someone else's love.But if this were a story about a man who, at the age of 40, attracted to a girl from a girls band, and the girl is 16 years younger than him, we would get stories about a disgusting creep who finds no other way to overcome his midlife crisis than preadatory pursue a girl, young enough to be his daughter."

In [23]:
df['reviews_tokenizadas'][0]

'film well reaction wonderful example modern hypocrisy story adult woman attracted young guy year younger young enough son see boy band concert people reaction start movie trailer beyond get praise story destruction stigma happiness woman remain attractive age man happiness available anyone u judge someone else story man age attracted girl girl band girl year younger would get story disgusting creep find way overcome midlife crisis preadatory pursue girl young enough daughter'

In [27]:
df.isna().sum()

Title                  0
Year                   0
Duration (min)         0
Genre                  0
Rating                 0
Metascore              0
Director               0
Cast                   0
Votes                  0
Description            0
Review Count           0
Review Title           0
Review                 0
metascore_missing      0
reviews_tokenizadas    0
dtype: int64

In [29]:
df[["Rating", "Metascore"]].describe()

            Rating    Metascore
count  9336.000000  9336.000000
mean      6.442063    58.072622
std       1.043144    15.921826
min       1.300000     1.000000
25%       5.800000    49.000000
50%       6.500000    58.000000
75%       7.200000    68.000000
max       9.700000   100.000000

In [30]:
df

,Title,Year,Duration (min),Genre,Rating,Metascore,Director,Cast,Votes,Description,Review Count,Review Title,Review,metascore_missing,reviews_tokenizadas
0,The Idea of You,2023.0,115.0,"Comedy, Drama, Romance",6.4,67.0,Michael Showalter,"Anne Hathaway, Nicholas Galitzine, Ella Rubin,...","28,744","Solène, a 40-year-old single mom, begins an un...",166,Hypocrisy as an idea,"This film, as well as the reaction to it, is a...",0,film well reaction wonderful example modern hy...
1,Kingdom of the Planet of the Apes,2023.0,145.0,"Action, Adventure, Sci-Fi",7.3,66.0,Wes Ball,"Owen Teague, Freya Allan, Kevin Durand, Peter ...","22,248","Many years after the reign of Caesar, a young ...",183,A phenomenal start to another trilogy!,"I'm a big fan of all the planet of the apes, a...",0,big fan planet ape nailed one usually start mi...
2,Unfrosted,2023.0,97.0,"Biography, Comedy, History",5.5,42.0,Jerry Seinfeld,"Isaac Bae, Jerry Seinfeld, Chris Rickett, Rach...","18,401","In 1963 Michigan, business rivals Kellogg's an...",333,not funny,Pretty much the worst criticism you can lay on...,0,pretty much worst criticism lay comedian true ...
3,The Fall Guy,2023.0,126.0,"Action, Comedy, Drama",7.3,73.0,David Leitch,"Ryan Gosling, Emily Blunt, Aaron Taylor-Johnso...","38,953",A down-and-out stuntman must find the missing ...,384,Everything you needed and more!,Just got out of the Austin premier at SXSW and...,0,got austin premier sxsw whole theatre went nut...
4,Challengers,2023.0,131.0,"Drama, Romance, Sport",7.7,82.0,Luca Guadagnino,"Zendaya, Mike Faist, Josh O'Connor, Darnell Ap...","32,517","Tashi, a former tennis prodigy turned coach, t...",194,"Watch ""Match Point"" instead",This is a tough one. I liked the concept and t...,0,tough one liked concept overall story however ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,The Greatest Show on Earth,2020.0,152.0,"Drama, Family, Romance",6.5,76.0,Cecil B. DeMille,"James Stewart, Charlton Heston, Betty Hutton, ...","16,078","The dramatic lives of trapeze artists, a clown...",128,"Hey, doesn't anyone remember Last Emperor?",It constantly amazes me that people carp that ...,0,constantly amazes people carp best picture tho...
9996,Berserk: Ougon Jidai-hen I - Haou no Tamago,2020.0,76.0,"Animation, Action, Adventure",7.5,58.0,Toshiyuki Kubooka,"Hiroaki Iwanaga, Carrie Keranen, Takahiro Saku...","14,300",A lone sellsword named Guts gets recruited int...,12,Masterfully directed climatic epic saga,Few stories can capture your mind and soul in ...,1,story capture mind soul visceral way beginning...
9997,Is-slottet,2020.0,78.0,"Mystery, Drama",6.5,58.0,Per Blom,"Line Storesund, Hilde Nyeggen Martinsen, Meret...",740,A couple of twelve-year-old Norwegian girls st...,4,Beautiful Film,"This film might not be to everyone's taste, it...",1,film might everyone taste slow moving like goo...
9998,Loving Pablo,2020.0,123.0,"Biography, Crime, Drama",6.4,42.0,Fernando León de Aranoa,"Javier Bardem, Penélope Cruz, Peter Sarsgaard,...","22,447",A journalist strikes up a romantic relationshi...,84,That film should be in Spanish,Why anyone (the director?) made Spanish actors...,0,anyone director made spanish actor speak bad e...
9999,Un homme et une femme,2020.0,102.0,"Drama, Romance",7.5,58.0,Claude Lelouch,"Anouk Aimée, Jean-Louis Trintignant, Pierre Ba...","11,826",A widow and a widower find their relationship ...,61,Moved me tremendously.,This is a movie that resonated to my core. I ...,1,movie resonated core identified main character...

In [34]:
df.to_csv("../data/processed/imdb_clean.csv", index=False)